### ISSUE TITLE
erreur sur le code 

### ISSUE THREAD

**Issue by Kryp3tek** [Baptiste-mrch/Discord-Mail-Bot#1]
hello, here I use your  code but I have this error which happens every time ->

future: <Task finished name='Task-1' coro=<check_new_mail() done, defined at c:\Users\kryp3tek\Desktop\projet bot discord\main.py:59> exception=error("SELECT command error: BAD [b'Could not parse command']")>
Traceback (most recent call last):
  File "c:\Users\kryp3tek\Desktop\projet bot discord\main.py", line 64, in check_new_mail
    mail.select(mail_label)
  File "D:\python\lib\imaplib.py", line 756, in select
    typ, dat = self._simple_command(name, mailbox)
  File "D:\python\lib\imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "D:\python\lib\imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: SELECT command error: BAD [b'Could not parse command']

thank you

**Comment by Baptiste-mrch** [comment]
Hello,
Thanks for your reporting.

Do you have change the "mail_label" variable at the top of the code ?
If your want to scan the entire mailbox, fill it with "INBOX" so the code scan the inbox folder of your mailbox.
If you apply filter like I was doing using Gmail, fill it with the name of your label.

I hope this will helping you

**Comment by Kryp3tek** [comment]
j'aurais une autre question je le fait tourner en local avec Visual studio code et j'aurais voulu savoir si je pouvais rajouter une boucle qui fait que sa regarde a chaque foi si jai pas un mail c'est possible ?

**Comment by Baptiste-mrch** [comment]
Normalement le code, une fois lancé, le fait de lui même grâce à des fonctions Async

**Comment by Kryp3tek** [comment]
ok ok 
nice merci encore pour ton code tres propre  et tres utile pour moi =D

**Comment by Baptiste-mrch** [comment]
No problem 😉
